language: android
android:
  components:
    - build-tools-19.0.3
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
script:
  - ./gradlew assembleDebug
