language: java

sudo: false

#cache:
#  directories:
#    - $HOME/.m2

before_script:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME

jdk:
  - openjdk7
#  - oraclejdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    - MALLOC_ARENA_MAX=2
  matrix:
    - JTRCI='lib/ruby/truffle/jruby+truffle/gem_ci/travis.txt'
    - PHASE='-Ptest'
    - PHASE='-Prake -Dtask=test:jruby'
    - PHASE='-Prake -Dtask=test:jruby:fullint'
    - PHASE='-Prake -Dtask=test:jruby:jit'
    - PHASE='-Prake -Dtask=test:mri'
    - PHASE='-Prake -Dtask=test:mri:fullint'
    - PHASE='-Prake -Dtask=test:mri:jit'
    - PHASE='-Prake -Dtask=test:slow_suites'
    - PHASE='-Prake -Dtask=test:tracing'
    - PHASE='-Prake -Dtask=spec:ji'
    - PHASE='-Prake -Dtask=spec:compiler'
    - PHASE='-Prake -Dtask=spec:ffi'
    - PHASE='-Prake -Dtask=spec:regression'
    - PHASE='-Prake -Dtask=spec:ruby:fast'
    - PHASE='-Prake -Dtask=spec:jruby'
    - PHASE='-Prake -Dtask=spec:jrubyc'
    - PHASE='-Prake -Dtask=spec:profiler'
    - JT='test specs :language'
    - JT='test specs :core'
    - JT='test specs :library'
    - JT='test specs :truffle'
    - JT='test integration'

matrix:
  include:
    # these profile do no need to run for all JDKs
    - env: PHASE='-Pdist'
      jdk: oraclejdk8
    - env: PHASE='-Pjruby-jars'
      jdk: openjdk7
    - env: PHASE='-Pmain'
      jdk: oraclejdk8
    - env: PHASE='-Pcomplete'
      jdk: oraclejdk8
    - env: PHASE='-Posgi'
      jdk: openjdk7
    - env: PHASE='-Pj2ee'
      jdk: oraclejdk7
    # These next two started crashing on JDK7 in March 2015, possibly due to JVM issues on Travis's Docker-based env
    - env: PHASE='-Pjruby-jars,test -Dinvoker.test=extended'
      jdk: oraclejdk8
    - env: PHASE='-Pmain,test -Dinvoker.test=extended'
      jdk: oraclejdk8
    - env: PHASE='-Pjruby_complete_jar_extended -Dinvoker.skip=true'
      jdk: oraclejdk8
    - env: COMMAND=test/check_versions.sh
      jdk: oraclejdk8
    #- env: JT=check_ambiguous_arguments
    #  jdk: oraclejdk8
  allow_failures:
    - env: PHASE='-Prake -Dtask=test:mri:fullint'
    - env: JT=check_ambiguous_arguments
      jdk: oraclejdk8
    - env: JT='test mri'
    - env: JTRCI='lib/ruby/truffle/jruby+truffle/gem_ci/travis.txt'
    # NOTE: build seems to never start (waited for any to finish for more than a day) - probably a travis-ci bug
    #- env: PHASE='-Pmain'
    #  sudo: required
    #  dist: trusty
    #  group: edge
    #  jdk: oraclejdk9

branches:
  only:
    - master
    - jruby-1_7
    - truffle-head
    - /^test-.*$/
    - /^ha-feature/
    - ruby-2.3

script: tool/travis_runner.sh
install: travis_retry ./mvnw -Pbootstrap clean install -B -Dinvoker.skip -Dmaven.test.skip

notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

  # update jruby-head installed on Travis CI
  webhooks:
    urls:
      - "https://rubies.travis-ci.org/rebuild/jruby-head"
# we are on a branch
    on_success: always
    on_failure: never
