+language: ruby
+rvm:
+  - 1.9.3
+  - 2.1.0
+script:
+  - ruby --version
+  - echo test1
+  - echo test2
 % travis encrypt DEPLOYGATE_TOKEN=7c6cd1c8f6870875f836a7cb085c2dad57605455
 env:
  global:
    - secure:7c6cd1c8f6870875f836a7cb085c2dad57605455
 #after_success:
  - if [ "${TRAVIS_BRANCH}" = "develop" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then curl -F "file=@${TRAVIS_BUILD_DIR}/build/apk/Servermanagerdaiso.apk" -F "token=${DEPLOYGATE_TOKEN}" https://deploygate.com/users/Tom463/apps/ ;fi 
