+language: ruby
+rvm:
+  - 1.9.3
+  - 2.1.0
+script:
+  - ruby --version

#after_success:
  - if [ "${TRAVIS_BRANCH}" = "develop" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then curl -F "file=@${TRAVIS_BUILD_DIR}/build/apk/Servermanagerdaiso.apk" -F "token=${DEPLOYGATE_TOKEN}"　http://ux.getuploader.com/nora_apk/index/1/filename/ ;fi
