language: android  
android:  
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:  
  - ./gradlew assembleRelease
deploy:  
  provider: releases
  api_key:
    secure: [生成的token]
  file: app/build/outputs/apk/serermanager.apk
  skip_cleanup: true
  on:
    tags: true
