language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - '.*intel.+'
 
branches:
  only:
    - master
 
before_install:
  - android list sdk --no-ui --all --extended
 
script:
  - ./gradlew assembleDebug
 
#after_success:http://up2.karinto.in/uploader/
